// Shared TypeScript interfaces for all viz components.
// Every component in components/viz/ imports from here.
// Do not duplicate these inline — keep the source of truth here.

/**
 * A row of `fixtures/corridor-rents.json` — owned by the cre-swfl
 * `corridor_profiles` table. Regenerated by `npm run fixtures:corridors`.
 * Rent + vacancy + absorption only. Permits / centroid data lives in
 * separate domain-owned fixtures (see below).
 */
export interface CorridorEntry {
  id: string;
  name: string;
  submarket: string;
  nnn_asking_rent_per_sqft: number | null;
  vacancy_pct: number | null;
  absorption_sqft: number | null;
}

/**
 * A row of `fixtures/corridor-permits.json` — owned by the permits-swfl pack
 * sidecar (Stage 4 emit). Lee-only by structural reality; Collier corridors
 * have no entry here. `corridor_id` is the centroid namespace; bridge to
 * cre-swfl slugs via `refinery/lib/corridor-aliases.mts`.
 */
export interface CorridorPermitsEntry {
  corridor_id: string;
  headline_z: number;
  n_current: number;
  last_refined_at: string;
}

/**
 * A row of `fixtures/corridor-centroids.json` — hand-authored Lee corridor
 * centroids. Same namespace as CorridorPermitsEntry.corridor_id; the alias
 * table maps cre-swfl slugs → centroid corridor_ids.
 */
export interface CorridorCentroidEntry {
  corridor_id: string;
  corridor_label: string;
  center_lat: number;
  center_lon: number;
  submarket: string;
}

/**
 * Merged shape consumed by the embed-time viz components. Produced once by
 * `app/embed/charts/page.tsx` (single canonical join site) — walks the
 * alias table and joins rent rows with their optional permit + centroid
 * data. `permits === null` means "known no-coverage" (Collier corridor);
 * downstream code renders the "no permits coverage" badge.
 */
export interface JoinedCorridorRow {
  id: string;
  name: string;
  submarket: string;
  nnn_asking_rent_per_sqft: number | null;
  vacancy_pct: number | null;
  absorption_sqft: number | null;
  permits: CorridorPermitsEntry | null;
  centroid: CorridorCentroidEntry | null;
}

export interface ZHVIMonth {
  month: string; // "YYYY-MM"
  cape_coral: number | null;
  fort_myers: number | null;
  naples: number | null;
}

// Non-nullable version of ZHVIMonth used for chart rendering (nulls filtered before passing in).
export interface ZHVITrendEntry {
  month: string; // "YYYY-MM"
  cape_coral: number;
  fort_myers: number;
  naples: number;
}

export interface ZORIEntry {
  zip: string;
  city: string;
  county: string;
  trend: { month: string; rent: number }[];
}

export interface KeyMetric {
  label: string;
  value: string;
  trend: "up" | "down" | "flat";
  change_pct: number;
}

export interface BrainOutput {
  id: string;
  conclusion: string;
  confidence: number; // 0–1
  freshness_token: string;
  updated_at: string;
  sources_count: number;
  key_metrics: KeyMetric[];
  caveats: string[];
}

export interface PermitMonth {
  month: string; // "YYYY-MM"
  zscore: number;
}

export interface PermitHeatmapRow {
  corridor: string;
  months: PermitMonth[];
}

export interface VizStats {
  corridors_tracked: number;
  sqft_analyzed: number;
  data_sources: number;
  swfl_zips: number;
  flood_records: number;
  brain_confidence: number;
}
